// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	kraken "github.com/skip-mev/connect-mmu/market-indexer/ingesters/kraken"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// AssetPairs provides a mock function with given fields: ctx
func (_m *Client) AssetPairs(ctx context.Context) (kraken.AssetPairsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AssetPairs")
	}

	var r0 kraken.AssetPairsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (kraken.AssetPairsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) kraken.AssetPairsResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(kraken.AssetPairsResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_AssetPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssetPairs'
type Client_AssetPairs_Call struct {
	*mock.Call
}

// AssetPairs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) AssetPairs(ctx interface{}) *Client_AssetPairs_Call {
	return &Client_AssetPairs_Call{Call: _e.mock.On("AssetPairs", ctx)}
}

func (_c *Client_AssetPairs_Call) Run(run func(ctx context.Context)) *Client_AssetPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_AssetPairs_Call) Return(_a0 kraken.AssetPairsResponse, _a1 error) *Client_AssetPairs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_AssetPairs_Call) RunAndReturn(run func(context.Context) (kraken.AssetPairsResponse, error)) *Client_AssetPairs_Call {
	_c.Call.Return(run)
	return _c
}

// Tickers provides a mock function with given fields: ctx
func (_m *Client) Tickers(ctx context.Context) (kraken.TickersResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Tickers")
	}

	var r0 kraken.TickersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (kraken.TickersResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) kraken.TickersResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(kraken.TickersResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_Tickers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tickers'
type Client_Tickers_Call struct {
	*mock.Call
}

// Tickers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) Tickers(ctx interface{}) *Client_Tickers_Call {
	return &Client_Tickers_Call{Call: _e.mock.On("Tickers", ctx)}
}

func (_c *Client_Tickers_Call) Run(run func(ctx context.Context)) *Client_Tickers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_Tickers_Call) Return(_a0 kraken.TickersResponse, _a1 error) *Client_Tickers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_Tickers_Call) RunAndReturn(run func(context.Context) (kraken.TickersResponse, error)) *Client_Tickers_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
