// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	dydx "github.com/skip-mev/connect-mmu/client/dydx"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// AllPerpetuals provides a mock function with given fields: ctx
func (_m *Client) AllPerpetuals(ctx context.Context) (*dydx.AllPerpetualsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllPerpetuals")
	}

	var r0 *dydx.AllPerpetualsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*dydx.AllPerpetualsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *dydx.AllPerpetualsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dydx.AllPerpetualsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_AllPerpetuals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllPerpetuals'
type Client_AllPerpetuals_Call struct {
	*mock.Call
}

// AllPerpetuals is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) AllPerpetuals(ctx interface{}) *Client_AllPerpetuals_Call {
	return &Client_AllPerpetuals_Call{Call: _e.mock.On("AllPerpetuals", ctx)}
}

func (_c *Client_AllPerpetuals_Call) Run(run func(ctx context.Context)) *Client_AllPerpetuals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_AllPerpetuals_Call) Return(_a0 *dydx.AllPerpetualsResponse, _a1 error) *Client_AllPerpetuals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_AllPerpetuals_Call) RunAndReturn(run func(context.Context) (*dydx.AllPerpetualsResponse, error)) *Client_AllPerpetuals_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
